
#include "RGB.h"

#define   POT_R		POTONTIOMETER1
#define   POT_G		POTONTIOMETER2
#define   POT_B		POTONTIOMETER3

void RGB_Init ()
{
	DIO_Init();
	ADC_Init(ADC_VCC, ADC_PRESCALER_8);
	TIMER0_Init(TIMER0_PRESCALER_8, TIMER0_FAST_PWM, TIMER0_OC0_CLEAR_ON_COMPARE_MATCH);
	TIMER1_Init(TIMER1_PRESCALER_8, TIMER1_FAST_PWM_8BIT, TIMER1_OC1A_CLEAR_ON_COMPARE_MATCH, TIMER1_OC1B_CLEAR_ON_COMPARE_MATCH);
	
	ADC_Enable();
}

void RGB_Run ()
{
	RGB_LED(POTONTIOMETER_Red(), POTONTIOMETER_Green(), POTONTIOMETER_Blue());
}

u8 POTONTIOMETER_Red ()
{
	return (POT_R () * 255.0)/100.0;
}

u8 POTONTIOMETER_Green ()
{
	return (POT_G () * 255.0)/100.0;
}

u8 POTONTIOMETER_Blue ()
{
	return (POT_B () * 255.0)/100.0;
}
